# Generated by Django 2.0.4 on 2018-05-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='album',
        ),
        migrations.DeleteModel(
            name='albumartist',
        ),
        migrations.DeleteModel(
            name='artist',
        ),
        migrations.DeleteModel(
            name='files',
        ),
        migrations.DeleteModel(
            name='song',
        ),
    ]
